### ISSUE TITLE
Extension has trouble saving code.

### ISSUE THREAD

**Issue by wutadamyt** [Ruud14/Page-Manipulator#11]
After a seemingly random amount of time, any code written within the extension will just randomly decide not to save and there doesn't seem to be any way to combat this without completely removing the extension from Chrome and re-adding it.

**Comment by Ruud14** [comment]
Hi @wutadamyt , 

First of all, thanks for reporting the  issue.
This sounds a lot like a bug that was fixed in October 2020 where files over +/- 8000 characters couldn't be saved
due to the fact that the the chrome synced storage has a content limit per file. 
Back then this was fixed by saving files over 8000 characters locally instead of synced. 

However you mention that files are not saving after a certain amount of time instead of when they exceed 8000 characters.
Are you sure that this happens after a certain amount of time and not when exceeding +/-8000 characters?
If so, does the saving not work on one file, all files, or the whole extension (Including which file is the last opened file etc.)?
Also, has this happened multiple times now or how often does this issue occur?

Finally, if this happens again, could you right click **inside** the extension -> 'inspect element' -> 'console' and tell me what errors (if any) you are seeing.
