### ISSUE TITLE
Error: "The tag name provided is not a valid name"

### ISSUE THREAD

**Issue by mvanleeu** [Ruud14/Page-Manipulator#2]
Hi,

I try to manipulate a webpage by adding "name" attributes to some inputs, to allow password managers like BitWarden to complete the right fields.
I've added for the targeted page a javascript manipulator, like below:
> setTimeout(function() { 
> 	document.querySelector("some selector").name = "username";
> 	document.querySelector("some other selector").name = "dutyCode";
> 	console.log("Added missing field names");
> }, 3000);

**Side question**: is that the best way to execute something once the page has loaded? Trying to set event listener on the document fails, as the js is executed before the document elements exists.

Now if the timeout value is too low, or if I try other methodologies like:
> setTimeout(function() { 
>     document.addEventListener('readystatechange', () => console.log(document.readyState));
> }, 1);

I then get strange errors in the console, which somehow seem to remain even if I "_correct_" the javascript to add a higher timeout...
The exact error I get in my particular case is:

> Error handling response: Error: Failed to execute 'createElement' on 'Document': The tag name provided ('page-manipulator-Sell Connect') is not a valid name.
>     at manipulate (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:209:45)
>     at load_data_from_storage (chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:85:17)
>     at chrome-extension://mdhellggnoabbnnchkeniomkpghbekko/content.js:95:9

I suspect that  the space between "Sell" and "Connect" is causing the issue, but this is not something I control. Unfortunately the website is an intranet site, so I cannot send you to this exact example, but I can check whatever you need to identify the issue.

**Comment by Ruud14** [comment]
I managed to recreate the error you are getting. 
In my test case, I created an HTML file inside the chrome extension. The filename of this file contains a ' ' character. So this means there is a bug in the chrome extension. This shouldn't be a problem in your case though, since you are trying to inject JavaScript instead of HTML.

This might sound a bit stupid but it seems like you have done the following:
- created an HTML file in the chrome extension. (This HTML file has a filename that contains a ' ' character) 
- put JavaScript code inside of the HTML file.
- Injected the JavaScript code as if it is HTML code.

So to (hopefully) get your code working, you should put your JavaScript code in a JavaScript file by doing the following:
- Go back to the main menu of the chrome extension (press 'back' in the top left corner of the extension if you aren't on the main menu already.)
- Click "JavaScript".
- Click "+ New +".
- Enter a filename and press 'Make'.
- Paste your code and manipulate the page.

I hope this solves your problem :)

Answer to your side question:
This definitely is an easy way of doing it but the page doesn't change immediately.
A way to change the page somewhat immediately is by creating a loop that constantly checks for the existence of a specific element on the page. If it finds that element that means the page is loaded and the page can be changed.

Hope this helps!

**Comment by mvanleeu** [comment]
I followed the instruction and deleted all scripts / html snipnets ( I think they were none though), and recreated the code as javascript. Unfortunately, the error message remains the same.
Originally, I did create an HTML file though, but I though I delete it afterwards.

Is there a way to make sure ALL previous snipnets are deleted?

**Comment by Ruud14** [comment]
To make sure all snippets are deleted you can do the following:
- open the chrome extension.
- right-click **inside** of the chrome extension window and click 'inspect'.
A chrome devtools window should pop up with the HTML contents of the chrome extension inside of it.
- In the top navigation bar of this devtools window click on 'console'. 
- In the console execute the following commands: 
- `chrome.storage.sync.clear();` and `chrome.storage.local.clear();`.
- Close the devtools window and the chrome extension.
All snippets should be deleted now.

**Comment by mvanleeu** [comment]
That worked to clear all snippets. Dank je wel (="Thanks").

Will now try out different methodologies to execute the necessary changes as soon as the page is loaded, but adding a hook of some sort so that the code executes after the page is loaded (and I know how many definitions there are on when that is) would be a nice addition.

**Comment by Ruud14** [comment]
Kijk eens aan, ook een Nederlander ;)

I will look into adding some kind of hook so that the user can choose if the code should be injected before or after the page is loaded. This is kinda difficult though since pages often load parts using JavaScript.
I think that's why I let the users of the extension decide for themselves on when their JavaScript code should be executed.

If you have any more issues or feature requests, just let me know.
