### ISSUE TITLE
Extension doesnot detect URL changes in a webapp navigation

### ISSUE THREAD

**Issue by Akash-116** [Ruud14/Page-Manipulator#22]
I am using a webapp where a navigation bar with some tabs are present. Clicking on these tabs changes the main webpage content and the URL in the top search bar of chrome browser, but this doesn't seem to refresh your extension. 

I mean, the extension is supposed to work on the new URL but it doesnot! **When I reload the page then it starts working**, and continues to work when I move to the old page (where the extension is supposed to be disabled) using webapp navigation. Reloading on the old url then disables the extesion. 

Maybe the eventHandler needs to be changed so that URL changes are detected even in a webapp navigation.

**Comment by Ruud14** [comment]
You're absolutely right.
The problem is that these websites dynamically change their content and the extension doesn't reinject code when the page has changed dynamically.

In your scenario, you would like to reinject (or re-execute part of ) your code, though this is not always what the user wants. 
For example, websites also often change the URL when applying search filters for some search. It would not be practical to have the extension reinject the code every time the user clicks on a search filter.

**There might still be a possible way of achieving what you want though.**
After the page has dynamically changed, the injected javascript is most likely still present (the <script> tags are).
This means that you, in your code, could listen for URL changes (e.g. using the `locationchange` event listener). 
Then once a locationchange event is triggered, you could re-execute part of your code, to reapply the changes to the page.

Hope this helps!

**Comment by Akash-116** [comment]
Ah yes! This is just what I needed. Thank you for the reply Ruud. Please feel free to close this issue. 👍👍
