### ISSUE TITLE
Inspect Element

### ISSUE THREAD

**Issue by zavvvv** [Ruud14/Page-Manipulator#30]
Hello. All I want to do is to change elements through inspect element, and than use page manipulator to save the changes so when i reload it keep the same values for elements . How can I do this. I am complete beginner.

**Comment by Ruud14** [comment]
Hi,

You'd have to write a few lines of javascript or CSS to make the changes you want, instead of changing them using inspect element by hand. 

This might be daunting as a beginner, so I'd recommend you read [this comment](https://github.com/Ruud14/Page-Manipulator/issues/15#issuecomment-1011872950) I wrote for another beginner to see how something similar can be done. 
Afterwards you could read [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents), a simple javascript DOM manipulation guide that could have you start writing your own script for what you want.
