### ISSUE TITLE
VM559:1 Uncaught TypeError: Cannot set property 'textContent' of null     at <anonymous>:1:57

### ISSUE THREAD

**Issue by Naiym223** [Ruud14/Page-Manipulator#5]
Javascript: `document.getElementById("nav-robux-balance").textContent="41,821 Robux";`

Page: https://www.roblox.com/home

**Comment by Ruud14** [comment]
The element you are trying to get is not present on the page, hence you are getting the TypeError.
The element might not be on the page because:
- The Id of the element is wrong. Double check if "nav-robux-balance" is right.
- You are trying to get the element before the element is present on the page. You could try adding a delay to avoid this. The simplest example would be something like this:
```
    setTimeout(function () {
        document.getElementById("nav-robux-balance").textContent="41,821 Robux";
    }, 2000);
```
