### ISSUE TITLE
Unexpected behavior of Active / Auto load feature

### ISSUE THREAD

**Issue by derek-lowery** [Ruud14/Page-Manipulator#6]
Hey there,

I'm hoping you'll be able to clarify if this is bug, or if I'm overlooking something.

1. If page manipulator is 'On' and working, if I browser refresh / f5, page manipulator stops working, and I have to go in, and click 'manipulate' to start it up again.
2. Similar to 1, if I have page manipulator running, and I close the browser completely, open a new browser instance, navigate to the site I have defined in the setup, and nothing happens because it's turned 'off'.

3. Is that expected behavior? Ideally, I don't want to have to remember to turn on / activate page manipulator each time I open a new browser.
4.  And if the page manipulator is running, and it already  has manipulated the page, when you hit f5 / browser refresh, it's the same behavior as if you open a completely new browser instance - the manipulator starts at an 'off' state.

**Comment by Ruud14** [comment]
The thing that you want to achieve is the whole point of my extension so the problems you are having are either bugs, or you are doing something wrong. 

I'd like you to test this simple example:

Please create a new CSS file inside the extension (name it whatever you want) and change the settings and content to what is shown below.
![image](https://user-images.githubusercontent.com/40769366/126874181-e22bccdf-9294-4c1d-b068-5fbb9178bed8.png)

Now visit google.com

Since the 'active' checkbox is checked and the 'active websites' textfield contains 'google.com', the website 'google.com' should now have a blue background. This blue background should still be there after every reload or visit on the page.

Please try this simple example and let me know if this works or not.

**Comment by derek-lowery** [comment]
Okay so using your example I was able to get it working correctly and was also helpful in determining what was causing my issue.

I didn't notice the site I was configuring has a redirect that drops the 'www' from the URL.
I was entering the active website with the full URL e.g. 'https://www.site.com' so Page Manipulator would work fine on the first apply.  Then reloading / refreshing would cause a failure because the configuration was looking for a path that contained 'www'. 

So in closing, using the format 'site.com' solves any issues I had.

Thanks for the quick reply, and thanks for making such a great utility sir.

**Comment by Ruud14** [comment]
I'm glad to hear I could help and thank you for using the extension.
